/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: java.security.spec.ECPrivateKeySpec
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_SECURITY_SPEC_ECPRIVATEKEYSPEC_HPP_DECL
#define J2CPP_JAVA_SECURITY_SPEC_ECPRIVATEKEYSPEC_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace security { namespace spec { class KeySpec; } } } }
namespace j2cpp { namespace java { namespace security { namespace spec { class ECParameterSpec; } } } }
namespace j2cpp { namespace java { namespace math { class BigInteger; } } }


#include <java/lang/Object.hpp>
#include <java/math/BigInteger.hpp>
#include <java/security/spec/ECParameterSpec.hpp>
#include <java/security/spec/KeySpec.hpp>


namespace j2cpp {

namespace java { namespace security { namespace spec {

	class ECPrivateKeySpec;
	class ECPrivateKeySpec
		: public object<ECPrivateKeySpec>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)

		explicit ECPrivateKeySpec(jobject jobj)
		: object<ECPrivateKeySpec>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;
		operator local_ref<java::security::spec::KeySpec>() const;


		ECPrivateKeySpec(local_ref< java::math::BigInteger > const&, local_ref< java::security::spec::ECParameterSpec > const&);
		local_ref< java::security::spec::ECParameterSpec > getParams();
		local_ref< java::math::BigInteger > getS();
	}; //class ECPrivateKeySpec

} //namespace spec
} //namespace security
} //namespace java

} //namespace j2cpp

#endif //J2CPP_JAVA_SECURITY_SPEC_ECPRIVATEKEYSPEC_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_SECURITY_SPEC_ECPRIVATEKEYSPEC_HPP_IMPL
#define J2CPP_JAVA_SECURITY_SPEC_ECPRIVATEKEYSPEC_HPP_IMPL

namespace j2cpp {



java::security::spec::ECPrivateKeySpec::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

java::security::spec::ECPrivateKeySpec::operator local_ref<java::security::spec::KeySpec>() const
{
	return local_ref<java::security::spec::KeySpec>(get_jobject());
}


java::security::spec::ECPrivateKeySpec::ECPrivateKeySpec(local_ref< java::math::BigInteger > const &a0, local_ref< java::security::spec::ECParameterSpec > const &a1)
: object<java::security::spec::ECPrivateKeySpec>(
	call_new_object<
		java::security::spec::ECPrivateKeySpec::J2CPP_CLASS_NAME,
		java::security::spec::ECPrivateKeySpec::J2CPP_METHOD_NAME(0),
		java::security::spec::ECPrivateKeySpec::J2CPP_METHOD_SIGNATURE(0)
	>(a0, a1)
)
{
}


local_ref< java::security::spec::ECParameterSpec > java::security::spec::ECPrivateKeySpec::getParams()
{
	return call_method<
		java::security::spec::ECPrivateKeySpec::J2CPP_CLASS_NAME,
		java::security::spec::ECPrivateKeySpec::J2CPP_METHOD_NAME(1),
		java::security::spec::ECPrivateKeySpec::J2CPP_METHOD_SIGNATURE(1), 
		local_ref< java::security::spec::ECParameterSpec >
	>(get_jobject());
}

local_ref< java::math::BigInteger > java::security::spec::ECPrivateKeySpec::getS()
{
	return call_method<
		java::security::spec::ECPrivateKeySpec::J2CPP_CLASS_NAME,
		java::security::spec::ECPrivateKeySpec::J2CPP_METHOD_NAME(2),
		java::security::spec::ECPrivateKeySpec::J2CPP_METHOD_SIGNATURE(2), 
		local_ref< java::math::BigInteger >
	>(get_jobject());
}


J2CPP_DEFINE_CLASS(java::security::spec::ECPrivateKeySpec,"java/security/spec/ECPrivateKeySpec")
J2CPP_DEFINE_METHOD(java::security::spec::ECPrivateKeySpec,0,"<init>","(Ljava/math/BigInteger;Ljava/security/spec/ECParameterSpec;)V")
J2CPP_DEFINE_METHOD(java::security::spec::ECPrivateKeySpec,1,"getParams","()Ljava/security/spec/ECParameterSpec;")
J2CPP_DEFINE_METHOD(java::security::spec::ECPrivateKeySpec,2,"getS","()Ljava/math/BigInteger;")

} //namespace j2cpp

#endif //J2CPP_JAVA_SECURITY_SPEC_ECPRIVATEKEYSPEC_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
