/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: javax.security.auth.login.LoginException
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVAX_SECURITY_AUTH_LOGIN_LOGINEXCEPTION_HPP_DECL
#define J2CPP_JAVAX_SECURITY_AUTH_LOGIN_LOGINEXCEPTION_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class Exception; } } }
namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Throwable; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace security { class GeneralSecurityException; } } }
namespace j2cpp { namespace java { namespace io { class Serializable; } } }


#include <java/io/Serializable.hpp>
#include <java/lang/Exception.hpp>
#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>
#include <java/lang/Throwable.hpp>
#include <java/security/GeneralSecurityException.hpp>


namespace j2cpp {

namespace javax { namespace security { namespace auth { namespace login {

	class LoginException;
	class LoginException
		: public object<LoginException>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)

		explicit LoginException(jobject jobj)
		: object<LoginException>(jobj)
		{
		}

		operator local_ref<java::lang::Exception>() const;
		operator local_ref<java::lang::Throwable>() const;
		operator local_ref<java::lang::Object>() const;
		operator local_ref<java::security::GeneralSecurityException>() const;
		operator local_ref<java::io::Serializable>() const;


		LoginException();
		LoginException(local_ref< java::lang::String > const&);
	}; //class LoginException

} //namespace login
} //namespace auth
} //namespace security
} //namespace javax

} //namespace j2cpp

#endif //J2CPP_JAVAX_SECURITY_AUTH_LOGIN_LOGINEXCEPTION_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVAX_SECURITY_AUTH_LOGIN_LOGINEXCEPTION_HPP_IMPL
#define J2CPP_JAVAX_SECURITY_AUTH_LOGIN_LOGINEXCEPTION_HPP_IMPL

namespace j2cpp {



javax::security::auth::login::LoginException::operator local_ref<java::lang::Exception>() const
{
	return local_ref<java::lang::Exception>(get_jobject());
}

javax::security::auth::login::LoginException::operator local_ref<java::lang::Throwable>() const
{
	return local_ref<java::lang::Throwable>(get_jobject());
}

javax::security::auth::login::LoginException::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

javax::security::auth::login::LoginException::operator local_ref<java::security::GeneralSecurityException>() const
{
	return local_ref<java::security::GeneralSecurityException>(get_jobject());
}

javax::security::auth::login::LoginException::operator local_ref<java::io::Serializable>() const
{
	return local_ref<java::io::Serializable>(get_jobject());
}


javax::security::auth::login::LoginException::LoginException()
: object<javax::security::auth::login::LoginException>(
	call_new_object<
		javax::security::auth::login::LoginException::J2CPP_CLASS_NAME,
		javax::security::auth::login::LoginException::J2CPP_METHOD_NAME(0),
		javax::security::auth::login::LoginException::J2CPP_METHOD_SIGNATURE(0)
	>()
)
{
}



javax::security::auth::login::LoginException::LoginException(local_ref< java::lang::String > const &a0)
: object<javax::security::auth::login::LoginException>(
	call_new_object<
		javax::security::auth::login::LoginException::J2CPP_CLASS_NAME,
		javax::security::auth::login::LoginException::J2CPP_METHOD_NAME(1),
		javax::security::auth::login::LoginException::J2CPP_METHOD_SIGNATURE(1)
	>(a0)
)
{
}



J2CPP_DEFINE_CLASS(javax::security::auth::login::LoginException,"javax/security/auth/login/LoginException")
J2CPP_DEFINE_METHOD(javax::security::auth::login::LoginException,0,"<init>","()V")
J2CPP_DEFINE_METHOD(javax::security::auth::login::LoginException,1,"<init>","(Ljava/lang/String;)V")

} //namespace j2cpp

#endif //J2CPP_JAVAX_SECURITY_AUTH_LOGIN_LOGINEXCEPTION_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
