/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: java.security.cert.CollectionCertStoreParameters
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_SECURITY_CERT_COLLECTIONCERTSTOREPARAMETERS_HPP_DECL
#define J2CPP_JAVA_SECURITY_CERT_COLLECTIONCERTSTOREPARAMETERS_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace lang { class Cloneable; } } }
namespace j2cpp { namespace java { namespace security { namespace cert { class CertStoreParameters; } } } }
namespace j2cpp { namespace java { namespace util { class Collection; } } }


#include <java/lang/Cloneable.hpp>
#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>
#include <java/security/cert/CertStoreParameters.hpp>
#include <java/util/Collection.hpp>


namespace j2cpp {

namespace java { namespace security { namespace cert {

	class CollectionCertStoreParameters;
	class CollectionCertStoreParameters
		: public object<CollectionCertStoreParameters>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)

		explicit CollectionCertStoreParameters(jobject jobj)
		: object<CollectionCertStoreParameters>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;
		operator local_ref<java::lang::Cloneable>() const;
		operator local_ref<java::security::cert::CertStoreParameters>() const;


		CollectionCertStoreParameters();
		CollectionCertStoreParameters(local_ref< java::util::Collection > const&);
		local_ref< java::lang::Object > clone();
		local_ref< java::util::Collection > getCollection();
		local_ref< java::lang::String > toString();
	}; //class CollectionCertStoreParameters

} //namespace cert
} //namespace security
} //namespace java

} //namespace j2cpp

#endif //J2CPP_JAVA_SECURITY_CERT_COLLECTIONCERTSTOREPARAMETERS_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_SECURITY_CERT_COLLECTIONCERTSTOREPARAMETERS_HPP_IMPL
#define J2CPP_JAVA_SECURITY_CERT_COLLECTIONCERTSTOREPARAMETERS_HPP_IMPL

namespace j2cpp {



java::security::cert::CollectionCertStoreParameters::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

java::security::cert::CollectionCertStoreParameters::operator local_ref<java::lang::Cloneable>() const
{
	return local_ref<java::lang::Cloneable>(get_jobject());
}

java::security::cert::CollectionCertStoreParameters::operator local_ref<java::security::cert::CertStoreParameters>() const
{
	return local_ref<java::security::cert::CertStoreParameters>(get_jobject());
}


java::security::cert::CollectionCertStoreParameters::CollectionCertStoreParameters()
: object<java::security::cert::CollectionCertStoreParameters>(
	call_new_object<
		java::security::cert::CollectionCertStoreParameters::J2CPP_CLASS_NAME,
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_NAME(0),
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_SIGNATURE(0)
	>()
)
{
}



java::security::cert::CollectionCertStoreParameters::CollectionCertStoreParameters(local_ref< java::util::Collection > const &a0)
: object<java::security::cert::CollectionCertStoreParameters>(
	call_new_object<
		java::security::cert::CollectionCertStoreParameters::J2CPP_CLASS_NAME,
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_NAME(1),
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_SIGNATURE(1)
	>(a0)
)
{
}


local_ref< java::lang::Object > java::security::cert::CollectionCertStoreParameters::clone()
{
	return call_method<
		java::security::cert::CollectionCertStoreParameters::J2CPP_CLASS_NAME,
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_NAME(2),
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_SIGNATURE(2), 
		local_ref< java::lang::Object >
	>(get_jobject());
}

local_ref< java::util::Collection > java::security::cert::CollectionCertStoreParameters::getCollection()
{
	return call_method<
		java::security::cert::CollectionCertStoreParameters::J2CPP_CLASS_NAME,
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_NAME(3),
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_SIGNATURE(3), 
		local_ref< java::util::Collection >
	>(get_jobject());
}

local_ref< java::lang::String > java::security::cert::CollectionCertStoreParameters::toString()
{
	return call_method<
		java::security::cert::CollectionCertStoreParameters::J2CPP_CLASS_NAME,
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_NAME(4),
		java::security::cert::CollectionCertStoreParameters::J2CPP_METHOD_SIGNATURE(4), 
		local_ref< java::lang::String >
	>(get_jobject());
}


J2CPP_DEFINE_CLASS(java::security::cert::CollectionCertStoreParameters,"java/security/cert/CollectionCertStoreParameters")
J2CPP_DEFINE_METHOD(java::security::cert::CollectionCertStoreParameters,0,"<init>","()V")
J2CPP_DEFINE_METHOD(java::security::cert::CollectionCertStoreParameters,1,"<init>","(Ljava/util/Collection;)V")
J2CPP_DEFINE_METHOD(java::security::cert::CollectionCertStoreParameters,2,"clone","()Ljava/lang/Object;")
J2CPP_DEFINE_METHOD(java::security::cert::CollectionCertStoreParameters,3,"getCollection","()Ljava/util/Collection;")
J2CPP_DEFINE_METHOD(java::security::cert::CollectionCertStoreParameters,4,"toString","()Ljava/lang/String;")

} //namespace j2cpp

#endif //J2CPP_JAVA_SECURITY_CERT_COLLECTIONCERTSTOREPARAMETERS_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
