/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: android.view.VelocityTracker
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_VIEW_VELOCITYTRACKER_HPP_DECL
#define J2CPP_ANDROID_VIEW_VELOCITYTRACKER_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace android { namespace view { class MotionEvent; } } }


#include <android/view/MotionEvent.hpp>
#include <java/lang/Object.hpp>


namespace j2cpp {

namespace android { namespace view {

	class VelocityTracker;
	class VelocityTracker
		: public object<VelocityTracker>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_METHOD(7)
		J2CPP_DECLARE_METHOD(8)
		J2CPP_DECLARE_METHOD(9)
		J2CPP_DECLARE_METHOD(10)

		explicit VelocityTracker(jobject jobj)
		: object<VelocityTracker>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;


		static local_ref< android::view::VelocityTracker > obtain();
		void recycle();
		void clear();
		void addMovement(local_ref< android::view::MotionEvent >  const&);
		void computeCurrentVelocity(jint);
		void computeCurrentVelocity(jint, jfloat);
		jfloat getXVelocity();
		jfloat getYVelocity();
		jfloat getXVelocity(jint);
		jfloat getYVelocity(jint);
	}; //class VelocityTracker

} //namespace view
} //namespace android

} //namespace j2cpp

#endif //J2CPP_ANDROID_VIEW_VELOCITYTRACKER_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_VIEW_VELOCITYTRACKER_HPP_IMPL
#define J2CPP_ANDROID_VIEW_VELOCITYTRACKER_HPP_IMPL

namespace j2cpp {



android::view::VelocityTracker::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}


local_ref< android::view::VelocityTracker > android::view::VelocityTracker::obtain()
{
	return call_static_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(1),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(1), 
		local_ref< android::view::VelocityTracker >
	>();
}

void android::view::VelocityTracker::recycle()
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(2),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(2), 
		void
	>(get_jobject());
}

void android::view::VelocityTracker::clear()
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(3),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(3), 
		void
	>(get_jobject());
}

void android::view::VelocityTracker::addMovement(local_ref< android::view::MotionEvent > const &a0)
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(4),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(4), 
		void
	>(get_jobject(), a0);
}

void android::view::VelocityTracker::computeCurrentVelocity(jint a0)
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(5),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(5), 
		void
	>(get_jobject(), a0);
}

void android::view::VelocityTracker::computeCurrentVelocity(jint a0, jfloat a1)
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(6),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(6), 
		void
	>(get_jobject(), a0, a1);
}

jfloat android::view::VelocityTracker::getXVelocity()
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(7),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(7), 
		jfloat
	>(get_jobject());
}

jfloat android::view::VelocityTracker::getYVelocity()
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(8),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(8), 
		jfloat
	>(get_jobject());
}

jfloat android::view::VelocityTracker::getXVelocity(jint a0)
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(9),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(9), 
		jfloat
	>(get_jobject(), a0);
}

jfloat android::view::VelocityTracker::getYVelocity(jint a0)
{
	return call_method<
		android::view::VelocityTracker::J2CPP_CLASS_NAME,
		android::view::VelocityTracker::J2CPP_METHOD_NAME(10),
		android::view::VelocityTracker::J2CPP_METHOD_SIGNATURE(10), 
		jfloat
	>(get_jobject(), a0);
}


J2CPP_DEFINE_CLASS(android::view::VelocityTracker,"android/view/VelocityTracker")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,0,"<init>","()V")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,1,"obtain","()Landroid/view/VelocityTracker;")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,2,"recycle","()V")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,3,"clear","()V")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,4,"addMovement","(Landroid/view/MotionEvent;)V")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,5,"computeCurrentVelocity","(I)V")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,6,"computeCurrentVelocity","(IF)V")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,7,"getXVelocity","()F")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,8,"getYVelocity","()F")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,9,"getXVelocity","(I)F")
J2CPP_DEFINE_METHOD(android::view::VelocityTracker,10,"getYVelocity","(I)F")

} //namespace j2cpp

#endif //J2CPP_ANDROID_VIEW_VELOCITYTRACKER_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
