/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: android.app.Activity
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_APP_ACTIVITY_HPP_DECL
#define J2CPP_ANDROID_APP_ACTIVITY_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class CharSequence; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace lang { class Runnable; } } }
namespace j2cpp { namespace android { namespace content { class SharedPreferences; } } }
namespace j2cpp { namespace android { namespace content { class Intent; } } }
namespace j2cpp { namespace android { namespace content { class IntentSender; } } }
namespace j2cpp { namespace android { namespace content { class ComponentName; } } }
namespace j2cpp { namespace android { namespace content { class Context; } } }
namespace j2cpp { namespace android { namespace content { namespace res { class Configuration; } } } }
namespace j2cpp { namespace android { namespace content { class ComponentCallbacks; } } }
namespace j2cpp { namespace android { namespace content { class ContextWrapper; } } }
namespace j2cpp { namespace android { namespace util { class AttributeSet; } } }
namespace j2cpp { namespace android { namespace app { class PendingIntent; } } }
namespace j2cpp { namespace android { namespace app { class Application; } } }
namespace j2cpp { namespace android { namespace database { class Cursor; } } }
namespace j2cpp { namespace android { namespace net { class Uri; } } }
namespace j2cpp { namespace android { namespace view { class View; } } }
namespace j2cpp { namespace android { namespace view { class Window; } } }
namespace j2cpp { namespace android { namespace view { class LayoutInflater; } } }
namespace j2cpp { namespace android { namespace view { namespace LayoutInflater_ { class Factory; } } } }
namespace j2cpp { namespace android { namespace view { class KeyEvent; } } }
namespace j2cpp { namespace android { namespace view { class MenuItem; } } }
namespace j2cpp { namespace android { namespace view { class MenuInflater; } } }
namespace j2cpp { namespace android { namespace view { class ContextMenu; } } }
namespace j2cpp { namespace android { namespace view { namespace ContextMenu_ { class ContextMenuInfo; } } } }
namespace j2cpp { namespace android { namespace view { namespace View_ { class OnCreateContextMenuListener; } } } }
namespace j2cpp { namespace android { namespace view { namespace accessibility { class AccessibilityEvent; } } } }
namespace j2cpp { namespace android { namespace view { class Menu; } } }
namespace j2cpp { namespace android { namespace view { class MotionEvent; } } }
namespace j2cpp { namespace android { namespace view { class WindowManager; } } }
namespace j2cpp { namespace android { namespace view { namespace Window_ { class Callback; } } } }
namespace j2cpp { namespace android { namespace view { namespace ViewGroup_ { class LayoutParams; } } } }
namespace j2cpp { namespace android { namespace view { namespace WindowManager_ { class LayoutParams; } } } }
namespace j2cpp { namespace android { namespace view { class ContextThemeWrapper; } } }
namespace j2cpp { namespace android { namespace os { class Bundle; } } }
namespace j2cpp { namespace android { namespace graphics { class Canvas; } } }
namespace j2cpp { namespace android { namespace graphics { class Bitmap; } } }
namespace j2cpp { namespace android { namespace graphics { namespace drawable { class Drawable; } } } }


#include <android/app/Application.hpp>
#include <android/app/PendingIntent.hpp>
#include <android/content/ComponentCallbacks.hpp>
#include <android/content/ComponentName.hpp>
#include <android/content/Context.hpp>
#include <android/content/ContextWrapper.hpp>
#include <android/content/Intent.hpp>
#include <android/content/IntentSender.hpp>
#include <android/content/SharedPreferences.hpp>
#include <android/content/res/Configuration.hpp>
#include <android/database/Cursor.hpp>
#include <android/graphics/Bitmap.hpp>
#include <android/graphics/Canvas.hpp>
#include <android/graphics/drawable/Drawable.hpp>
#include <android/net/Uri.hpp>
#include <android/os/Bundle.hpp>
#include <android/util/AttributeSet.hpp>
#include <android/view/ContextMenu.hpp>
#include <android/view/ContextThemeWrapper.hpp>
#include <android/view/KeyEvent.hpp>
#include <android/view/LayoutInflater.hpp>
#include <android/view/Menu.hpp>
#include <android/view/MenuInflater.hpp>
#include <android/view/MenuItem.hpp>
#include <android/view/MotionEvent.hpp>
#include <android/view/View.hpp>
#include <android/view/ViewGroup.hpp>
#include <android/view/Window.hpp>
#include <android/view/WindowManager.hpp>
#include <android/view/accessibility/AccessibilityEvent.hpp>
#include <java/lang/CharSequence.hpp>
#include <java/lang/Object.hpp>
#include <java/lang/Runnable.hpp>
#include <java/lang/String.hpp>


namespace j2cpp {

namespace android { namespace app {

	class Activity;
	class Activity
		: public object<Activity>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_METHOD(7)
		J2CPP_DECLARE_METHOD(8)
		J2CPP_DECLARE_METHOD(9)
		J2CPP_DECLARE_METHOD(10)
		J2CPP_DECLARE_METHOD(11)
		J2CPP_DECLARE_METHOD(12)
		J2CPP_DECLARE_METHOD(13)
		J2CPP_DECLARE_METHOD(14)
		J2CPP_DECLARE_METHOD(15)
		J2CPP_DECLARE_METHOD(16)
		J2CPP_DECLARE_METHOD(17)
		J2CPP_DECLARE_METHOD(18)
		J2CPP_DECLARE_METHOD(19)
		J2CPP_DECLARE_METHOD(20)
		J2CPP_DECLARE_METHOD(21)
		J2CPP_DECLARE_METHOD(22)
		J2CPP_DECLARE_METHOD(23)
		J2CPP_DECLARE_METHOD(24)
		J2CPP_DECLARE_METHOD(25)
		J2CPP_DECLARE_METHOD(26)
		J2CPP_DECLARE_METHOD(27)
		J2CPP_DECLARE_METHOD(28)
		J2CPP_DECLARE_METHOD(29)
		J2CPP_DECLARE_METHOD(30)
		J2CPP_DECLARE_METHOD(31)
		J2CPP_DECLARE_METHOD(32)
		J2CPP_DECLARE_METHOD(33)
		J2CPP_DECLARE_METHOD(34)
		J2CPP_DECLARE_METHOD(35)
		J2CPP_DECLARE_METHOD(36)
		J2CPP_DECLARE_METHOD(37)
		J2CPP_DECLARE_METHOD(38)
		J2CPP_DECLARE_METHOD(39)
		J2CPP_DECLARE_METHOD(40)
		J2CPP_DECLARE_METHOD(41)
		J2CPP_DECLARE_METHOD(42)
		J2CPP_DECLARE_METHOD(43)
		J2CPP_DECLARE_METHOD(44)
		J2CPP_DECLARE_METHOD(45)
		J2CPP_DECLARE_METHOD(46)
		J2CPP_DECLARE_METHOD(47)
		J2CPP_DECLARE_METHOD(48)
		J2CPP_DECLARE_METHOD(49)
		J2CPP_DECLARE_METHOD(50)
		J2CPP_DECLARE_METHOD(51)
		J2CPP_DECLARE_METHOD(52)
		J2CPP_DECLARE_METHOD(53)
		J2CPP_DECLARE_METHOD(54)
		J2CPP_DECLARE_METHOD(55)
		J2CPP_DECLARE_METHOD(56)
		J2CPP_DECLARE_METHOD(57)
		J2CPP_DECLARE_METHOD(58)
		J2CPP_DECLARE_METHOD(59)
		J2CPP_DECLARE_METHOD(60)
		J2CPP_DECLARE_METHOD(61)
		J2CPP_DECLARE_METHOD(62)
		J2CPP_DECLARE_METHOD(63)
		J2CPP_DECLARE_METHOD(64)
		J2CPP_DECLARE_METHOD(65)
		J2CPP_DECLARE_METHOD(66)
		J2CPP_DECLARE_METHOD(67)
		J2CPP_DECLARE_METHOD(68)
		J2CPP_DECLARE_METHOD(69)
		J2CPP_DECLARE_METHOD(70)
		J2CPP_DECLARE_METHOD(71)
		J2CPP_DECLARE_METHOD(72)
		J2CPP_DECLARE_METHOD(73)
		J2CPP_DECLARE_METHOD(74)
		J2CPP_DECLARE_METHOD(75)
		J2CPP_DECLARE_METHOD(76)
		J2CPP_DECLARE_METHOD(77)
		J2CPP_DECLARE_METHOD(78)
		J2CPP_DECLARE_METHOD(79)
		J2CPP_DECLARE_METHOD(80)
		J2CPP_DECLARE_METHOD(81)
		J2CPP_DECLARE_METHOD(82)
		J2CPP_DECLARE_METHOD(83)
		J2CPP_DECLARE_METHOD(84)
		J2CPP_DECLARE_METHOD(85)
		J2CPP_DECLARE_METHOD(86)
		J2CPP_DECLARE_METHOD(87)
		J2CPP_DECLARE_METHOD(88)
		J2CPP_DECLARE_METHOD(89)
		J2CPP_DECLARE_METHOD(90)
		J2CPP_DECLARE_METHOD(91)
		J2CPP_DECLARE_METHOD(92)
		J2CPP_DECLARE_METHOD(93)
		J2CPP_DECLARE_METHOD(94)
		J2CPP_DECLARE_METHOD(95)
		J2CPP_DECLARE_METHOD(96)
		J2CPP_DECLARE_METHOD(97)
		J2CPP_DECLARE_METHOD(98)
		J2CPP_DECLARE_METHOD(99)
		J2CPP_DECLARE_METHOD(100)
		J2CPP_DECLARE_METHOD(101)
		J2CPP_DECLARE_METHOD(102)
		J2CPP_DECLARE_METHOD(103)
		J2CPP_DECLARE_METHOD(104)
		J2CPP_DECLARE_METHOD(105)
		J2CPP_DECLARE_METHOD(106)
		J2CPP_DECLARE_METHOD(107)
		J2CPP_DECLARE_METHOD(108)
		J2CPP_DECLARE_METHOD(109)
		J2CPP_DECLARE_METHOD(110)
		J2CPP_DECLARE_METHOD(111)
		J2CPP_DECLARE_METHOD(112)
		J2CPP_DECLARE_METHOD(113)
		J2CPP_DECLARE_METHOD(114)
		J2CPP_DECLARE_METHOD(115)
		J2CPP_DECLARE_METHOD(116)
		J2CPP_DECLARE_METHOD(117)
		J2CPP_DECLARE_METHOD(118)
		J2CPP_DECLARE_METHOD(119)
		J2CPP_DECLARE_METHOD(120)
		J2CPP_DECLARE_METHOD(121)
		J2CPP_DECLARE_METHOD(122)
		J2CPP_DECLARE_METHOD(123)
		J2CPP_DECLARE_METHOD(124)
		J2CPP_DECLARE_METHOD(125)
		J2CPP_DECLARE_METHOD(126)
		J2CPP_DECLARE_METHOD(127)
		J2CPP_DECLARE_METHOD(128)
		J2CPP_DECLARE_METHOD(129)
		J2CPP_DECLARE_METHOD(130)
		J2CPP_DECLARE_METHOD(131)
		J2CPP_DECLARE_METHOD(132)
		J2CPP_DECLARE_METHOD(133)
		J2CPP_DECLARE_METHOD(134)
		J2CPP_DECLARE_METHOD(135)
		J2CPP_DECLARE_METHOD(136)
		J2CPP_DECLARE_METHOD(137)
		J2CPP_DECLARE_METHOD(138)
		J2CPP_DECLARE_METHOD(139)
		J2CPP_DECLARE_METHOD(140)
		J2CPP_DECLARE_METHOD(141)
		J2CPP_DECLARE_METHOD(142)
		J2CPP_DECLARE_METHOD(143)
		J2CPP_DECLARE_METHOD(144)
		J2CPP_DECLARE_METHOD(145)
		J2CPP_DECLARE_FIELD(0)
		J2CPP_DECLARE_FIELD(1)
		J2CPP_DECLARE_FIELD(2)
		J2CPP_DECLARE_FIELD(3)
		J2CPP_DECLARE_FIELD(4)
		J2CPP_DECLARE_FIELD(5)
		J2CPP_DECLARE_FIELD(6)
		J2CPP_DECLARE_FIELD(7)
		J2CPP_DECLARE_FIELD(8)

		explicit Activity(jobject jobj)
		: object<Activity>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;
		operator local_ref<android::content::Context>() const;
		operator local_ref<android::content::ComponentCallbacks>() const;
		operator local_ref<android::content::ContextWrapper>() const;
		operator local_ref<android::view::LayoutInflater_::Factory>() const;
		operator local_ref<android::view::View_::OnCreateContextMenuListener>() const;
		operator local_ref<android::view::Window_::Callback>() const;
		operator local_ref<android::view::ContextThemeWrapper>() const;


		Activity();
		static jlong getInstanceCount();
		local_ref< android::content::Intent > getIntent();
		void setIntent(local_ref< android::content::Intent >  const&);
		local_ref< android::app::Application > getApplication();
		jboolean isChild();
		local_ref< android::app::Activity > getParent();
		local_ref< android::view::WindowManager > getWindowManager();
		local_ref< android::view::Window > getWindow();
		local_ref< android::view::View > getCurrentFocus();
		jint getWallpaperDesiredMinimumWidth();
		jint getWallpaperDesiredMinimumHeight();
		jboolean onCreateThumbnail(local_ref< android::graphics::Bitmap >  const&, local_ref< android::graphics::Canvas >  const&);
		local_ref< java::lang::CharSequence > onCreateDescription();
		void onConfigurationChanged(local_ref< android::content::res::Configuration >  const&);
		jint getChangingConfigurations();
		local_ref< java::lang::Object > getLastNonConfigurationInstance();
		local_ref< java::lang::Object > onRetainNonConfigurationInstance();
		void onLowMemory();
		local_ref< android::database::Cursor > managedQuery(local_ref< android::net::Uri >  const&, local_ref< array< local_ref< java::lang::String >, 1> >  const&, local_ref< java::lang::String >  const&, local_ref< array< local_ref< java::lang::String >, 1> >  const&, local_ref< java::lang::String >  const&);
		void startManagingCursor(local_ref< android::database::Cursor >  const&);
		void stopManagingCursor(local_ref< android::database::Cursor >  const&);
		void setPersistent(jboolean);
		local_ref< android::view::View > findViewById(jint);
		void setContentView(jint);
		void setContentView(local_ref< android::view::View >  const&);
		void setContentView(local_ref< android::view::View >  const&, local_ref< android::view::ViewGroup_::LayoutParams >  const&);
		void addContentView(local_ref< android::view::View >  const&, local_ref< android::view::ViewGroup_::LayoutParams >  const&);
		void setDefaultKeyMode(jint);
		jboolean onKeyDown(jint, local_ref< android::view::KeyEvent >  const&);
		jboolean onKeyLongPress(jint, local_ref< android::view::KeyEvent >  const&);
		jboolean onKeyUp(jint, local_ref< android::view::KeyEvent >  const&);
		jboolean onKeyMultiple(jint, jint, local_ref< android::view::KeyEvent >  const&);
		void onBackPressed();
		jboolean onTouchEvent(local_ref< android::view::MotionEvent >  const&);
		jboolean onTrackballEvent(local_ref< android::view::MotionEvent >  const&);
		void onUserInteraction();
		void onWindowAttributesChanged(local_ref< android::view::WindowManager_::LayoutParams >  const&);
		void onContentChanged();
		void onWindowFocusChanged(jboolean);
		void onAttachedToWindow();
		void onDetachedFromWindow();
		jboolean hasWindowFocus();
		jboolean dispatchKeyEvent(local_ref< android::view::KeyEvent >  const&);
		jboolean dispatchTouchEvent(local_ref< android::view::MotionEvent >  const&);
		jboolean dispatchTrackballEvent(local_ref< android::view::MotionEvent >  const&);
		jboolean dispatchPopulateAccessibilityEvent(local_ref< android::view::accessibility::AccessibilityEvent >  const&);
		local_ref< android::view::View > onCreatePanelView(jint);
		jboolean onCreatePanelMenu(jint, local_ref< android::view::Menu >  const&);
		jboolean onPreparePanel(jint, local_ref< android::view::View >  const&, local_ref< android::view::Menu >  const&);
		jboolean onMenuOpened(jint, local_ref< android::view::Menu >  const&);
		jboolean onMenuItemSelected(jint, local_ref< android::view::MenuItem >  const&);
		void onPanelClosed(jint, local_ref< android::view::Menu >  const&);
		jboolean onCreateOptionsMenu(local_ref< android::view::Menu >  const&);
		jboolean onPrepareOptionsMenu(local_ref< android::view::Menu >  const&);
		jboolean onOptionsItemSelected(local_ref< android::view::MenuItem >  const&);
		void onOptionsMenuClosed(local_ref< android::view::Menu >  const&);
		void openOptionsMenu();
		void closeOptionsMenu();
		void onCreateContextMenu(local_ref< android::view::ContextMenu >  const&, local_ref< android::view::View >  const&, local_ref< android::view::ContextMenu_::ContextMenuInfo >  const&);
		void registerForContextMenu(local_ref< android::view::View >  const&);
		void unregisterForContextMenu(local_ref< android::view::View >  const&);
		void openContextMenu(local_ref< android::view::View >  const&);
		void closeContextMenu();
		jboolean onContextItemSelected(local_ref< android::view::MenuItem >  const&);
		void onContextMenuClosed(local_ref< android::view::Menu >  const&);
		void showDialog(jint);
		jboolean showDialog(jint, local_ref< android::os::Bundle >  const&);
		void dismissDialog(jint);
		void removeDialog(jint);
		jboolean onSearchRequested();
		void startSearch(local_ref< java::lang::String >  const&, jboolean, local_ref< android::os::Bundle >  const&, jboolean);
		void triggerSearch(local_ref< java::lang::String >  const&, local_ref< android::os::Bundle >  const&);
		void takeKeyEvents(jboolean);
		jboolean requestWindowFeature(jint);
		void setFeatureDrawableResource(jint, jint);
		void setFeatureDrawableUri(jint, local_ref< android::net::Uri >  const&);
		void setFeatureDrawable(jint, local_ref< android::graphics::drawable::Drawable >  const&);
		void setFeatureDrawableAlpha(jint, jint);
		local_ref< android::view::LayoutInflater > getLayoutInflater();
		local_ref< android::view::MenuInflater > getMenuInflater();
		void startActivityForResult(local_ref< android::content::Intent >  const&, jint);
		void startIntentSenderForResult(local_ref< android::content::IntentSender >  const&, jint, local_ref< android::content::Intent >  const&, jint, jint, jint);
		void startActivity(local_ref< android::content::Intent >  const&);
		void startIntentSender(local_ref< android::content::IntentSender >  const&, local_ref< android::content::Intent >  const&, jint, jint, jint);
		jboolean startActivityIfNeeded(local_ref< android::content::Intent >  const&, jint);
		jboolean startNextMatchingActivity(local_ref< android::content::Intent >  const&);
		void startActivityFromChild(local_ref< android::app::Activity >  const&, local_ref< android::content::Intent >  const&, jint);
		void startIntentSenderFromChild(local_ref< android::app::Activity >  const&, local_ref< android::content::IntentSender >  const&, jint, local_ref< android::content::Intent >  const&, jint, jint, jint);
		void overridePendingTransition(jint, jint);
		void setResult(jint);
		void setResult(jint, local_ref< android::content::Intent >  const&);
		local_ref< java::lang::String > getCallingPackage();
		local_ref< android::content::ComponentName > getCallingActivity();
		void setVisible(jboolean);
		jboolean isFinishing();
		void finish();
		void finishFromChild(local_ref< android::app::Activity >  const&);
		void finishActivity(jint);
		void finishActivityFromChild(local_ref< android::app::Activity >  const&, jint);
		local_ref< android::app::PendingIntent > createPendingResult(jint, local_ref< android::content::Intent >  const&, jint);
		void setRequestedOrientation(jint);
		jint getRequestedOrientation();
		jint getTaskId();
		jboolean isTaskRoot();
		jboolean moveTaskToBack(jboolean);
		local_ref< java::lang::String > getLocalClassName();
		local_ref< android::content::ComponentName > getComponentName();
		local_ref< android::content::SharedPreferences > getPreferences(jint);
		local_ref< java::lang::Object > getSystemService(local_ref< java::lang::String >  const&);
		void setTitle(local_ref< java::lang::CharSequence >  const&);
		void setTitle(jint);
		void setTitleColor(jint);
		local_ref< java::lang::CharSequence > getTitle();
		jint getTitleColor();
		void setProgressBarVisibility(jboolean);
		void setProgressBarIndeterminateVisibility(jboolean);
		void setProgressBarIndeterminate(jboolean);
		void setProgress(jint);
		void setSecondaryProgress(jint);
		void setVolumeControlStream(jint);
		jint getVolumeControlStream();
		void runOnUiThread(local_ref< java::lang::Runnable >  const&);
		local_ref< android::view::View > onCreateView(local_ref< java::lang::String >  const&, local_ref< android::content::Context >  const&, local_ref< android::util::AttributeSet >  const&);

		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(0), J2CPP_FIELD_SIGNATURE(0), jint > RESULT_CANCELED;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(1), J2CPP_FIELD_SIGNATURE(1), jint > RESULT_OK;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(2), J2CPP_FIELD_SIGNATURE(2), jint > RESULT_FIRST_USER;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(4), J2CPP_FIELD_SIGNATURE(4), jint > DEFAULT_KEYS_DISABLE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(5), J2CPP_FIELD_SIGNATURE(5), jint > DEFAULT_KEYS_DIALER;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(6), J2CPP_FIELD_SIGNATURE(6), jint > DEFAULT_KEYS_SHORTCUT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(7), J2CPP_FIELD_SIGNATURE(7), jint > DEFAULT_KEYS_SEARCH_LOCAL;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(8), J2CPP_FIELD_SIGNATURE(8), jint > DEFAULT_KEYS_SEARCH_GLOBAL;
	}; //class Activity

} //namespace app
} //namespace android

} //namespace j2cpp

#endif //J2CPP_ANDROID_APP_ACTIVITY_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_APP_ACTIVITY_HPP_IMPL
#define J2CPP_ANDROID_APP_ACTIVITY_HPP_IMPL

namespace j2cpp {



android::app::Activity::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

android::app::Activity::operator local_ref<android::content::Context>() const
{
	return local_ref<android::content::Context>(get_jobject());
}

android::app::Activity::operator local_ref<android::content::ComponentCallbacks>() const
{
	return local_ref<android::content::ComponentCallbacks>(get_jobject());
}

android::app::Activity::operator local_ref<android::content::ContextWrapper>() const
{
	return local_ref<android::content::ContextWrapper>(get_jobject());
}

android::app::Activity::operator local_ref<android::view::LayoutInflater_::Factory>() const
{
	return local_ref<android::view::LayoutInflater_::Factory>(get_jobject());
}

android::app::Activity::operator local_ref<android::view::View_::OnCreateContextMenuListener>() const
{
	return local_ref<android::view::View_::OnCreateContextMenuListener>(get_jobject());
}

android::app::Activity::operator local_ref<android::view::Window_::Callback>() const
{
	return local_ref<android::view::Window_::Callback>(get_jobject());
}

android::app::Activity::operator local_ref<android::view::ContextThemeWrapper>() const
{
	return local_ref<android::view::ContextThemeWrapper>(get_jobject());
}


android::app::Activity::Activity()
: object<android::app::Activity>(
	call_new_object<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(0),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(0)
	>()
)
{
}


jlong android::app::Activity::getInstanceCount()
{
	return call_static_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(1),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(1), 
		jlong
	>();
}

local_ref< android::content::Intent > android::app::Activity::getIntent()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(2),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(2), 
		local_ref< android::content::Intent >
	>(get_jobject());
}

void android::app::Activity::setIntent(local_ref< android::content::Intent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(3),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(3), 
		void
	>(get_jobject(), a0);
}

local_ref< android::app::Application > android::app::Activity::getApplication()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(4),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(4), 
		local_ref< android::app::Application >
	>(get_jobject());
}

jboolean android::app::Activity::isChild()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(5),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(5), 
		jboolean
	>(get_jobject());
}

local_ref< android::app::Activity > android::app::Activity::getParent()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(6),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(6), 
		local_ref< android::app::Activity >
	>(get_jobject());
}

local_ref< android::view::WindowManager > android::app::Activity::getWindowManager()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(7),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(7), 
		local_ref< android::view::WindowManager >
	>(get_jobject());
}

local_ref< android::view::Window > android::app::Activity::getWindow()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(8),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(8), 
		local_ref< android::view::Window >
	>(get_jobject());
}

local_ref< android::view::View > android::app::Activity::getCurrentFocus()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(9),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(9), 
		local_ref< android::view::View >
	>(get_jobject());
}

jint android::app::Activity::getWallpaperDesiredMinimumWidth()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(10),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(10), 
		jint
	>(get_jobject());
}

jint android::app::Activity::getWallpaperDesiredMinimumHeight()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(11),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(11), 
		jint
	>(get_jobject());
}












jboolean android::app::Activity::onCreateThumbnail(local_ref< android::graphics::Bitmap > const &a0, local_ref< android::graphics::Canvas > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(23),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(23), 
		jboolean
	>(get_jobject(), a0, a1);
}

local_ref< java::lang::CharSequence > android::app::Activity::onCreateDescription()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(24),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(24), 
		local_ref< java::lang::CharSequence >
	>(get_jobject());
}



void android::app::Activity::onConfigurationChanged(local_ref< android::content::res::Configuration > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(27),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(27), 
		void
	>(get_jobject(), a0);
}

jint android::app::Activity::getChangingConfigurations()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(28),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(28), 
		jint
	>(get_jobject());
}

local_ref< java::lang::Object > android::app::Activity::getLastNonConfigurationInstance()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(29),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(29), 
		local_ref< java::lang::Object >
	>(get_jobject());
}

local_ref< java::lang::Object > android::app::Activity::onRetainNonConfigurationInstance()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(30),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(30), 
		local_ref< java::lang::Object >
	>(get_jobject());
}

void android::app::Activity::onLowMemory()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(31),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(31), 
		void
	>(get_jobject());
}

local_ref< android::database::Cursor > android::app::Activity::managedQuery(local_ref< android::net::Uri > const &a0, local_ref< array< local_ref< java::lang::String >, 1> > const &a1, local_ref< java::lang::String > const &a2, local_ref< array< local_ref< java::lang::String >, 1> > const &a3, local_ref< java::lang::String > const &a4)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(32),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(32), 
		local_ref< android::database::Cursor >
	>(get_jobject(), a0, a1, a2, a3, a4);
}

void android::app::Activity::startManagingCursor(local_ref< android::database::Cursor > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(33),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(33), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::stopManagingCursor(local_ref< android::database::Cursor > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(34),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(34), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setPersistent(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(35),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(35), 
		void
	>(get_jobject(), a0);
}

local_ref< android::view::View > android::app::Activity::findViewById(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(36),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(36), 
		local_ref< android::view::View >
	>(get_jobject(), a0);
}

void android::app::Activity::setContentView(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(37),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(37), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setContentView(local_ref< android::view::View > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(38),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(38), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setContentView(local_ref< android::view::View > const &a0, local_ref< android::view::ViewGroup_::LayoutParams > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(39),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(39), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::addContentView(local_ref< android::view::View > const &a0, local_ref< android::view::ViewGroup_::LayoutParams > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(40),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(40), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::setDefaultKeyMode(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(41),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(41), 
		void
	>(get_jobject(), a0);
}

jboolean android::app::Activity::onKeyDown(jint a0, local_ref< android::view::KeyEvent > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(42),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(42), 
		jboolean
	>(get_jobject(), a0, a1);
}

jboolean android::app::Activity::onKeyLongPress(jint a0, local_ref< android::view::KeyEvent > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(43),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(43), 
		jboolean
	>(get_jobject(), a0, a1);
}

jboolean android::app::Activity::onKeyUp(jint a0, local_ref< android::view::KeyEvent > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(44),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(44), 
		jboolean
	>(get_jobject(), a0, a1);
}

jboolean android::app::Activity::onKeyMultiple(jint a0, jint a1, local_ref< android::view::KeyEvent > const &a2)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(45),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(45), 
		jboolean
	>(get_jobject(), a0, a1, a2);
}

void android::app::Activity::onBackPressed()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(46),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(46), 
		void
	>(get_jobject());
}

jboolean android::app::Activity::onTouchEvent(local_ref< android::view::MotionEvent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(47),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(47), 
		jboolean
	>(get_jobject(), a0);
}

jboolean android::app::Activity::onTrackballEvent(local_ref< android::view::MotionEvent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(48),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(48), 
		jboolean
	>(get_jobject(), a0);
}

void android::app::Activity::onUserInteraction()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(49),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(49), 
		void
	>(get_jobject());
}

void android::app::Activity::onWindowAttributesChanged(local_ref< android::view::WindowManager_::LayoutParams > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(50),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(50), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::onContentChanged()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(51),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(51), 
		void
	>(get_jobject());
}

void android::app::Activity::onWindowFocusChanged(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(52),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(52), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::onAttachedToWindow()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(53),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(53), 
		void
	>(get_jobject());
}

void android::app::Activity::onDetachedFromWindow()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(54),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(54), 
		void
	>(get_jobject());
}

jboolean android::app::Activity::hasWindowFocus()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(55),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(55), 
		jboolean
	>(get_jobject());
}

jboolean android::app::Activity::dispatchKeyEvent(local_ref< android::view::KeyEvent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(56),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(56), 
		jboolean
	>(get_jobject(), a0);
}

jboolean android::app::Activity::dispatchTouchEvent(local_ref< android::view::MotionEvent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(57),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(57), 
		jboolean
	>(get_jobject(), a0);
}

jboolean android::app::Activity::dispatchTrackballEvent(local_ref< android::view::MotionEvent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(58),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(58), 
		jboolean
	>(get_jobject(), a0);
}

jboolean android::app::Activity::dispatchPopulateAccessibilityEvent(local_ref< android::view::accessibility::AccessibilityEvent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(59),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(59), 
		jboolean
	>(get_jobject(), a0);
}

local_ref< android::view::View > android::app::Activity::onCreatePanelView(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(60),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(60), 
		local_ref< android::view::View >
	>(get_jobject(), a0);
}

jboolean android::app::Activity::onCreatePanelMenu(jint a0, local_ref< android::view::Menu > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(61),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(61), 
		jboolean
	>(get_jobject(), a0, a1);
}

jboolean android::app::Activity::onPreparePanel(jint a0, local_ref< android::view::View > const &a1, local_ref< android::view::Menu > const &a2)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(62),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(62), 
		jboolean
	>(get_jobject(), a0, a1, a2);
}

jboolean android::app::Activity::onMenuOpened(jint a0, local_ref< android::view::Menu > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(63),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(63), 
		jboolean
	>(get_jobject(), a0, a1);
}

jboolean android::app::Activity::onMenuItemSelected(jint a0, local_ref< android::view::MenuItem > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(64),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(64), 
		jboolean
	>(get_jobject(), a0, a1);
}

void android::app::Activity::onPanelClosed(jint a0, local_ref< android::view::Menu > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(65),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(65), 
		void
	>(get_jobject(), a0, a1);
}

jboolean android::app::Activity::onCreateOptionsMenu(local_ref< android::view::Menu > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(66),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(66), 
		jboolean
	>(get_jobject(), a0);
}

jboolean android::app::Activity::onPrepareOptionsMenu(local_ref< android::view::Menu > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(67),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(67), 
		jboolean
	>(get_jobject(), a0);
}

jboolean android::app::Activity::onOptionsItemSelected(local_ref< android::view::MenuItem > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(68),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(68), 
		jboolean
	>(get_jobject(), a0);
}

void android::app::Activity::onOptionsMenuClosed(local_ref< android::view::Menu > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(69),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(69), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::openOptionsMenu()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(70),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(70), 
		void
	>(get_jobject());
}

void android::app::Activity::closeOptionsMenu()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(71),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(71), 
		void
	>(get_jobject());
}

void android::app::Activity::onCreateContextMenu(local_ref< android::view::ContextMenu > const &a0, local_ref< android::view::View > const &a1, local_ref< android::view::ContextMenu_::ContextMenuInfo > const &a2)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(72),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(72), 
		void
	>(get_jobject(), a0, a1, a2);
}

void android::app::Activity::registerForContextMenu(local_ref< android::view::View > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(73),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(73), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::unregisterForContextMenu(local_ref< android::view::View > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(74),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(74), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::openContextMenu(local_ref< android::view::View > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(75),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(75), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::closeContextMenu()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(76),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(76), 
		void
	>(get_jobject());
}

jboolean android::app::Activity::onContextItemSelected(local_ref< android::view::MenuItem > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(77),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(77), 
		jboolean
	>(get_jobject(), a0);
}

void android::app::Activity::onContextMenuClosed(local_ref< android::view::Menu > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(78),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(78), 
		void
	>(get_jobject(), a0);
}





void android::app::Activity::showDialog(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(83),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(83), 
		void
	>(get_jobject(), a0);
}

jboolean android::app::Activity::showDialog(jint a0, local_ref< android::os::Bundle > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(84),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(84), 
		jboolean
	>(get_jobject(), a0, a1);
}

void android::app::Activity::dismissDialog(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(85),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(85), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::removeDialog(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(86),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(86), 
		void
	>(get_jobject(), a0);
}

jboolean android::app::Activity::onSearchRequested()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(87),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(87), 
		jboolean
	>(get_jobject());
}

void android::app::Activity::startSearch(local_ref< java::lang::String > const &a0, jboolean a1, local_ref< android::os::Bundle > const &a2, jboolean a3)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(88),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(88), 
		void
	>(get_jobject(), a0, a1, a2, a3);
}

void android::app::Activity::triggerSearch(local_ref< java::lang::String > const &a0, local_ref< android::os::Bundle > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(89),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(89), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::takeKeyEvents(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(90),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(90), 
		void
	>(get_jobject(), a0);
}

jboolean android::app::Activity::requestWindowFeature(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(91),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(91), 
		jboolean
	>(get_jobject(), a0);
}

void android::app::Activity::setFeatureDrawableResource(jint a0, jint a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(92),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(92), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::setFeatureDrawableUri(jint a0, local_ref< android::net::Uri > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(93),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(93), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::setFeatureDrawable(jint a0, local_ref< android::graphics::drawable::Drawable > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(94),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(94), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::setFeatureDrawableAlpha(jint a0, jint a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(95),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(95), 
		void
	>(get_jobject(), a0, a1);
}

local_ref< android::view::LayoutInflater > android::app::Activity::getLayoutInflater()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(96),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(96), 
		local_ref< android::view::LayoutInflater >
	>(get_jobject());
}

local_ref< android::view::MenuInflater > android::app::Activity::getMenuInflater()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(97),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(97), 
		local_ref< android::view::MenuInflater >
	>(get_jobject());
}


void android::app::Activity::startActivityForResult(local_ref< android::content::Intent > const &a0, jint a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(99),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(99), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::startIntentSenderForResult(local_ref< android::content::IntentSender > const &a0, jint a1, local_ref< android::content::Intent > const &a2, jint a3, jint a4, jint a5)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(100),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(100), 
		void
	>(get_jobject(), a0, a1, a2, a3, a4, a5);
}

void android::app::Activity::startActivity(local_ref< android::content::Intent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(101),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(101), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::startIntentSender(local_ref< android::content::IntentSender > const &a0, local_ref< android::content::Intent > const &a1, jint a2, jint a3, jint a4)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(102),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(102), 
		void
	>(get_jobject(), a0, a1, a2, a3, a4);
}

jboolean android::app::Activity::startActivityIfNeeded(local_ref< android::content::Intent > const &a0, jint a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(103),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(103), 
		jboolean
	>(get_jobject(), a0, a1);
}

jboolean android::app::Activity::startNextMatchingActivity(local_ref< android::content::Intent > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(104),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(104), 
		jboolean
	>(get_jobject(), a0);
}

void android::app::Activity::startActivityFromChild(local_ref< android::app::Activity > const &a0, local_ref< android::content::Intent > const &a1, jint a2)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(105),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(105), 
		void
	>(get_jobject(), a0, a1, a2);
}

void android::app::Activity::startIntentSenderFromChild(local_ref< android::app::Activity > const &a0, local_ref< android::content::IntentSender > const &a1, jint a2, local_ref< android::content::Intent > const &a3, jint a4, jint a5, jint a6)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(106),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(106), 
		void
	>(get_jobject(), a0, a1, a2, a3, a4, a5, a6);
}

void android::app::Activity::overridePendingTransition(jint a0, jint a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(107),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(107), 
		void
	>(get_jobject(), a0, a1);
}

void android::app::Activity::setResult(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(108),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(108), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setResult(jint a0, local_ref< android::content::Intent > const &a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(109),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(109), 
		void
	>(get_jobject(), a0, a1);
}

local_ref< java::lang::String > android::app::Activity::getCallingPackage()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(110),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(110), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< android::content::ComponentName > android::app::Activity::getCallingActivity()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(111),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(111), 
		local_ref< android::content::ComponentName >
	>(get_jobject());
}

void android::app::Activity::setVisible(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(112),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(112), 
		void
	>(get_jobject(), a0);
}

jboolean android::app::Activity::isFinishing()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(113),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(113), 
		jboolean
	>(get_jobject());
}

void android::app::Activity::finish()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(114),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(114), 
		void
	>(get_jobject());
}

void android::app::Activity::finishFromChild(local_ref< android::app::Activity > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(115),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(115), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::finishActivity(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(116),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(116), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::finishActivityFromChild(local_ref< android::app::Activity > const &a0, jint a1)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(117),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(117), 
		void
	>(get_jobject(), a0, a1);
}


local_ref< android::app::PendingIntent > android::app::Activity::createPendingResult(jint a0, local_ref< android::content::Intent > const &a1, jint a2)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(119),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(119), 
		local_ref< android::app::PendingIntent >
	>(get_jobject(), a0, a1, a2);
}

void android::app::Activity::setRequestedOrientation(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(120),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(120), 
		void
	>(get_jobject(), a0);
}

jint android::app::Activity::getRequestedOrientation()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(121),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(121), 
		jint
	>(get_jobject());
}

jint android::app::Activity::getTaskId()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(122),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(122), 
		jint
	>(get_jobject());
}

jboolean android::app::Activity::isTaskRoot()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(123),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(123), 
		jboolean
	>(get_jobject());
}

jboolean android::app::Activity::moveTaskToBack(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(124),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(124), 
		jboolean
	>(get_jobject(), a0);
}

local_ref< java::lang::String > android::app::Activity::getLocalClassName()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(125),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(125), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< android::content::ComponentName > android::app::Activity::getComponentName()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(126),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(126), 
		local_ref< android::content::ComponentName >
	>(get_jobject());
}

local_ref< android::content::SharedPreferences > android::app::Activity::getPreferences(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(127),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(127), 
		local_ref< android::content::SharedPreferences >
	>(get_jobject(), a0);
}

local_ref< java::lang::Object > android::app::Activity::getSystemService(local_ref< java::lang::String > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(128),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(128), 
		local_ref< java::lang::Object >
	>(get_jobject(), a0);
}

void android::app::Activity::setTitle(local_ref< java::lang::CharSequence > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(129),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(129), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setTitle(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(130),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(130), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setTitleColor(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(131),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(131), 
		void
	>(get_jobject(), a0);
}

local_ref< java::lang::CharSequence > android::app::Activity::getTitle()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(132),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(132), 
		local_ref< java::lang::CharSequence >
	>(get_jobject());
}

jint android::app::Activity::getTitleColor()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(133),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(133), 
		jint
	>(get_jobject());
}



void android::app::Activity::setProgressBarVisibility(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(136),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(136), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setProgressBarIndeterminateVisibility(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(137),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(137), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setProgressBarIndeterminate(jboolean a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(138),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(138), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setProgress(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(139),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(139), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setSecondaryProgress(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(140),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(140), 
		void
	>(get_jobject(), a0);
}

void android::app::Activity::setVolumeControlStream(jint a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(141),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(141), 
		void
	>(get_jobject(), a0);
}

jint android::app::Activity::getVolumeControlStream()
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(142),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(142), 
		jint
	>(get_jobject());
}

void android::app::Activity::runOnUiThread(local_ref< java::lang::Runnable > const &a0)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(143),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(143), 
		void
	>(get_jobject(), a0);
}

local_ref< android::view::View > android::app::Activity::onCreateView(local_ref< java::lang::String > const &a0, local_ref< android::content::Context > const &a1, local_ref< android::util::AttributeSet > const &a2)
{
	return call_method<
		android::app::Activity::J2CPP_CLASS_NAME,
		android::app::Activity::J2CPP_METHOD_NAME(144),
		android::app::Activity::J2CPP_METHOD_SIGNATURE(144), 
		local_ref< android::view::View >
	>(get_jobject(), a0, a1, a2);
}



static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(0),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(0),
	jint
> android::app::Activity::RESULT_CANCELED;

static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(1),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(1),
	jint
> android::app::Activity::RESULT_OK;

static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(2),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(2),
	jint
> android::app::Activity::RESULT_FIRST_USER;

static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(4),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(4),
	jint
> android::app::Activity::DEFAULT_KEYS_DISABLE;

static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(5),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(5),
	jint
> android::app::Activity::DEFAULT_KEYS_DIALER;

static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(6),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(6),
	jint
> android::app::Activity::DEFAULT_KEYS_SHORTCUT;

static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(7),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(7),
	jint
> android::app::Activity::DEFAULT_KEYS_SEARCH_LOCAL;

static_field<
	android::app::Activity::J2CPP_CLASS_NAME,
	android::app::Activity::J2CPP_FIELD_NAME(8),
	android::app::Activity::J2CPP_FIELD_SIGNATURE(8),
	jint
> android::app::Activity::DEFAULT_KEYS_SEARCH_GLOBAL;


J2CPP_DEFINE_CLASS(android::app::Activity,"android/app/Activity")
J2CPP_DEFINE_METHOD(android::app::Activity,0,"<init>","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,1,"getInstanceCount","()J")
J2CPP_DEFINE_METHOD(android::app::Activity,2,"getIntent","()Landroid/content/Intent;")
J2CPP_DEFINE_METHOD(android::app::Activity,3,"setIntent","(Landroid/content/Intent;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,4,"getApplication","()Landroid/app/Application;")
J2CPP_DEFINE_METHOD(android::app::Activity,5,"isChild","()Z")
J2CPP_DEFINE_METHOD(android::app::Activity,6,"getParent","()Landroid/app/Activity;")
J2CPP_DEFINE_METHOD(android::app::Activity,7,"getWindowManager","()Landroid/view/WindowManager;")
J2CPP_DEFINE_METHOD(android::app::Activity,8,"getWindow","()Landroid/view/Window;")
J2CPP_DEFINE_METHOD(android::app::Activity,9,"getCurrentFocus","()Landroid/view/View;")
J2CPP_DEFINE_METHOD(android::app::Activity,10,"getWallpaperDesiredMinimumWidth","()I")
J2CPP_DEFINE_METHOD(android::app::Activity,11,"getWallpaperDesiredMinimumHeight","()I")
J2CPP_DEFINE_METHOD(android::app::Activity,12,"onCreate","(Landroid/os/Bundle;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,13,"onRestoreInstanceState","(Landroid/os/Bundle;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,14,"onPostCreate","(Landroid/os/Bundle;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,15,"onStart","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,16,"onRestart","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,17,"onResume","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,18,"onPostResume","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,19,"onNewIntent","(Landroid/content/Intent;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,20,"onSaveInstanceState","(Landroid/os/Bundle;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,21,"onPause","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,22,"onUserLeaveHint","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,23,"onCreateThumbnail","(Landroid/graphics/Bitmap;Landroid/graphics/Canvas;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,24,"onCreateDescription","()Ljava/lang/CharSequence;")
J2CPP_DEFINE_METHOD(android::app::Activity,25,"onStop","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,26,"onDestroy","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,27,"onConfigurationChanged","(Landroid/content/res/Configuration;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,28,"getChangingConfigurations","()I")
J2CPP_DEFINE_METHOD(android::app::Activity,29,"getLastNonConfigurationInstance","()Ljava/lang/Object;")
J2CPP_DEFINE_METHOD(android::app::Activity,30,"onRetainNonConfigurationInstance","()Ljava/lang/Object;")
J2CPP_DEFINE_METHOD(android::app::Activity,31,"onLowMemory","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,32,"managedQuery","(Landroid/net/Uri;[java.lang.StringLjava/lang/String;[java.lang.StringLjava/lang/String;)Landroid/database/Cursor;")
J2CPP_DEFINE_METHOD(android::app::Activity,33,"startManagingCursor","(Landroid/database/Cursor;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,34,"stopManagingCursor","(Landroid/database/Cursor;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,35,"setPersistent","(Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,36,"findViewById","(I)Landroid/view/View;")
J2CPP_DEFINE_METHOD(android::app::Activity,37,"setContentView","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,38,"setContentView","(Landroid/view/View;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,39,"setContentView","(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,40,"addContentView","(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,41,"setDefaultKeyMode","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,42,"onKeyDown","(ILandroid/view/KeyEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,43,"onKeyLongPress","(ILandroid/view/KeyEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,44,"onKeyUp","(ILandroid/view/KeyEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,45,"onKeyMultiple","(IILandroid/view/KeyEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,46,"onBackPressed","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,47,"onTouchEvent","(Landroid/view/MotionEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,48,"onTrackballEvent","(Landroid/view/MotionEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,49,"onUserInteraction","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,50,"onWindowAttributesChanged","(Landroid/view/WindowManager$LayoutParams;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,51,"onContentChanged","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,52,"onWindowFocusChanged","(Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,53,"onAttachedToWindow","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,54,"onDetachedFromWindow","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,55,"hasWindowFocus","()Z")
J2CPP_DEFINE_METHOD(android::app::Activity,56,"dispatchKeyEvent","(Landroid/view/KeyEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,57,"dispatchTouchEvent","(Landroid/view/MotionEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,58,"dispatchTrackballEvent","(Landroid/view/MotionEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,59,"dispatchPopulateAccessibilityEvent","(Landroid/view/accessibility/AccessibilityEvent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,60,"onCreatePanelView","(I)Landroid/view/View;")
J2CPP_DEFINE_METHOD(android::app::Activity,61,"onCreatePanelMenu","(ILandroid/view/Menu;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,62,"onPreparePanel","(ILandroid/view/View;Landroid/view/Menu;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,63,"onMenuOpened","(ILandroid/view/Menu;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,64,"onMenuItemSelected","(ILandroid/view/MenuItem;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,65,"onPanelClosed","(ILandroid/view/Menu;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,66,"onCreateOptionsMenu","(Landroid/view/Menu;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,67,"onPrepareOptionsMenu","(Landroid/view/Menu;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,68,"onOptionsItemSelected","(Landroid/view/MenuItem;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,69,"onOptionsMenuClosed","(Landroid/view/Menu;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,70,"openOptionsMenu","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,71,"closeOptionsMenu","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,72,"onCreateContextMenu","(Landroid/view/ContextMenu;Landroid/view/View;Landroid/view/ContextMenu$ContextMenuInfo;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,73,"registerForContextMenu","(Landroid/view/View;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,74,"unregisterForContextMenu","(Landroid/view/View;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,75,"openContextMenu","(Landroid/view/View;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,76,"closeContextMenu","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,77,"onContextItemSelected","(Landroid/view/MenuItem;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,78,"onContextMenuClosed","(Landroid/view/Menu;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,79,"onCreateDialog","(I)Landroid/app/Dialog;")
J2CPP_DEFINE_METHOD(android::app::Activity,80,"onCreateDialog","(ILandroid/os/Bundle;)Landroid/app/Dialog;")
J2CPP_DEFINE_METHOD(android::app::Activity,81,"onPrepareDialog","(ILandroid/app/Dialog;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,82,"onPrepareDialog","(ILandroid/app/Dialog;Landroid/os/Bundle;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,83,"showDialog","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,84,"showDialog","(ILandroid/os/Bundle;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,85,"dismissDialog","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,86,"removeDialog","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,87,"onSearchRequested","()Z")
J2CPP_DEFINE_METHOD(android::app::Activity,88,"startSearch","(Ljava/lang/String;ZLandroid/os/Bundle;Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,89,"triggerSearch","(Ljava/lang/String;Landroid/os/Bundle;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,90,"takeKeyEvents","(Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,91,"requestWindowFeature","(I)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,92,"setFeatureDrawableResource","(II)V")
J2CPP_DEFINE_METHOD(android::app::Activity,93,"setFeatureDrawableUri","(ILandroid/net/Uri;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,94,"setFeatureDrawable","(ILandroid/graphics/drawable/Drawable;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,95,"setFeatureDrawableAlpha","(II)V")
J2CPP_DEFINE_METHOD(android::app::Activity,96,"getLayoutInflater","()Landroid/view/LayoutInflater;")
J2CPP_DEFINE_METHOD(android::app::Activity,97,"getMenuInflater","()Landroid/view/MenuInflater;")
J2CPP_DEFINE_METHOD(android::app::Activity,98,"onApplyThemeResource","(Landroid/content/res/Resources$Theme;IZ)V")
J2CPP_DEFINE_METHOD(android::app::Activity,99,"startActivityForResult","(Landroid/content/Intent;I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,100,"startIntentSenderForResult","(Landroid/content/IntentSender;ILandroid/content/Intent;III)V")
J2CPP_DEFINE_METHOD(android::app::Activity,101,"startActivity","(Landroid/content/Intent;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,102,"startIntentSender","(Landroid/content/IntentSender;Landroid/content/Intent;III)V")
J2CPP_DEFINE_METHOD(android::app::Activity,103,"startActivityIfNeeded","(Landroid/content/Intent;I)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,104,"startNextMatchingActivity","(Landroid/content/Intent;)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,105,"startActivityFromChild","(Landroid/app/Activity;Landroid/content/Intent;I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,106,"startIntentSenderFromChild","(Landroid/app/Activity;Landroid/content/IntentSender;ILandroid/content/Intent;III)V")
J2CPP_DEFINE_METHOD(android::app::Activity,107,"overridePendingTransition","(II)V")
J2CPP_DEFINE_METHOD(android::app::Activity,108,"setResult","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,109,"setResult","(ILandroid/content/Intent;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,110,"getCallingPackage","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(android::app::Activity,111,"getCallingActivity","()Landroid/content/ComponentName;")
J2CPP_DEFINE_METHOD(android::app::Activity,112,"setVisible","(Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,113,"isFinishing","()Z")
J2CPP_DEFINE_METHOD(android::app::Activity,114,"finish","()V")
J2CPP_DEFINE_METHOD(android::app::Activity,115,"finishFromChild","(Landroid/app/Activity;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,116,"finishActivity","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,117,"finishActivityFromChild","(Landroid/app/Activity;I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,118,"onActivityResult","(IILandroid/content/Intent;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,119,"createPendingResult","(ILandroid/content/Intent;I)Landroid/app/PendingIntent;")
J2CPP_DEFINE_METHOD(android::app::Activity,120,"setRequestedOrientation","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,121,"getRequestedOrientation","()I")
J2CPP_DEFINE_METHOD(android::app::Activity,122,"getTaskId","()I")
J2CPP_DEFINE_METHOD(android::app::Activity,123,"isTaskRoot","()Z")
J2CPP_DEFINE_METHOD(android::app::Activity,124,"moveTaskToBack","(Z)Z")
J2CPP_DEFINE_METHOD(android::app::Activity,125,"getLocalClassName","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(android::app::Activity,126,"getComponentName","()Landroid/content/ComponentName;")
J2CPP_DEFINE_METHOD(android::app::Activity,127,"getPreferences","(I)Landroid/content/SharedPreferences;")
J2CPP_DEFINE_METHOD(android::app::Activity,128,"getSystemService","(Ljava/lang/String;)Ljava/lang/Object;")
J2CPP_DEFINE_METHOD(android::app::Activity,129,"setTitle","(Ljava/lang/CharSequence;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,130,"setTitle","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,131,"setTitleColor","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,132,"getTitle","()Ljava/lang/CharSequence;")
J2CPP_DEFINE_METHOD(android::app::Activity,133,"getTitleColor","()I")
J2CPP_DEFINE_METHOD(android::app::Activity,134,"onTitleChanged","(Ljava/lang/CharSequence;I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,135,"onChildTitleChanged","(Landroid/app/Activity;Ljava/lang/CharSequence;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,136,"setProgressBarVisibility","(Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,137,"setProgressBarIndeterminateVisibility","(Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,138,"setProgressBarIndeterminate","(Z)V")
J2CPP_DEFINE_METHOD(android::app::Activity,139,"setProgress","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,140,"setSecondaryProgress","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,141,"setVolumeControlStream","(I)V")
J2CPP_DEFINE_METHOD(android::app::Activity,142,"getVolumeControlStream","()I")
J2CPP_DEFINE_METHOD(android::app::Activity,143,"runOnUiThread","(Ljava/lang/Runnable;)V")
J2CPP_DEFINE_METHOD(android::app::Activity,144,"onCreateView","(Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;")
J2CPP_DEFINE_METHOD(android::app::Activity,145,"<clinit>","()V")
J2CPP_DEFINE_FIELD(android::app::Activity,0,"RESULT_CANCELED","I")
J2CPP_DEFINE_FIELD(android::app::Activity,1,"RESULT_OK","I")
J2CPP_DEFINE_FIELD(android::app::Activity,2,"RESULT_FIRST_USER","I")
J2CPP_DEFINE_FIELD(android::app::Activity,3,"FOCUSED_STATE_SET","[I")
J2CPP_DEFINE_FIELD(android::app::Activity,4,"DEFAULT_KEYS_DISABLE","I")
J2CPP_DEFINE_FIELD(android::app::Activity,5,"DEFAULT_KEYS_DIALER","I")
J2CPP_DEFINE_FIELD(android::app::Activity,6,"DEFAULT_KEYS_SHORTCUT","I")
J2CPP_DEFINE_FIELD(android::app::Activity,7,"DEFAULT_KEYS_SEARCH_LOCAL","I")
J2CPP_DEFINE_FIELD(android::app::Activity,8,"DEFAULT_KEYS_SEARCH_GLOBAL","I")

} //namespace j2cpp

#endif //J2CPP_ANDROID_APP_ACTIVITY_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
