/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: org.apache.http.impl.cookie.DateUtils
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_IMPL_COOKIE_DATEUTILS_HPP_DECL
#define J2CPP_ORG_APACHE_HTTP_IMPL_COOKIE_DATEUTILS_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace util { class TimeZone; } } }
namespace j2cpp { namespace java { namespace util { class Date; } } }


#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>
#include <java/util/Date.hpp>
#include <java/util/TimeZone.hpp>


namespace j2cpp {

namespace org { namespace apache { namespace http { namespace impl { namespace cookie {

	class DateUtils;
	class DateUtils
		: public object<DateUtils>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_FIELD(0)
		J2CPP_DECLARE_FIELD(1)
		J2CPP_DECLARE_FIELD(2)
		J2CPP_DECLARE_FIELD(3)

		explicit DateUtils(jobject jobj)
		: object<DateUtils>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;


		static local_ref< java::util::Date > parseDate(local_ref< java::lang::String >  const&);
		static local_ref< java::util::Date > parseDate(local_ref< java::lang::String >  const&, local_ref< array< local_ref< java::lang::String >, 1> >  const&);
		static local_ref< java::util::Date > parseDate(local_ref< java::lang::String >  const&, local_ref< array< local_ref< java::lang::String >, 1> >  const&, local_ref< java::util::Date >  const&);
		static local_ref< java::lang::String > formatDate(local_ref< java::util::Date >  const&);
		static local_ref< java::lang::String > formatDate(local_ref< java::util::Date >  const&, local_ref< java::lang::String >  const&);

		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(0), J2CPP_FIELD_SIGNATURE(0), local_ref< java::lang::String > > PATTERN_RFC1123;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(1), J2CPP_FIELD_SIGNATURE(1), local_ref< java::lang::String > > PATTERN_RFC1036;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(2), J2CPP_FIELD_SIGNATURE(2), local_ref< java::lang::String > > PATTERN_ASCTIME;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(3), J2CPP_FIELD_SIGNATURE(3), local_ref< java::util::TimeZone > > GMT;
	}; //class DateUtils

} //namespace cookie
} //namespace impl
} //namespace http
} //namespace apache
} //namespace org

} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_IMPL_COOKIE_DATEUTILS_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_IMPL_COOKIE_DATEUTILS_HPP_IMPL
#define J2CPP_ORG_APACHE_HTTP_IMPL_COOKIE_DATEUTILS_HPP_IMPL

namespace j2cpp {



org::apache::http::impl::cookie::DateUtils::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}


local_ref< java::util::Date > org::apache::http::impl::cookie::DateUtils::parseDate(local_ref< java::lang::String > const &a0)
{
	return call_static_method<
		org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_NAME(1),
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_SIGNATURE(1), 
		local_ref< java::util::Date >
	>(a0);
}

local_ref< java::util::Date > org::apache::http::impl::cookie::DateUtils::parseDate(local_ref< java::lang::String > const &a0, local_ref< array< local_ref< java::lang::String >, 1> > const &a1)
{
	return call_static_method<
		org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_NAME(2),
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_SIGNATURE(2), 
		local_ref< java::util::Date >
	>(a0, a1);
}

local_ref< java::util::Date > org::apache::http::impl::cookie::DateUtils::parseDate(local_ref< java::lang::String > const &a0, local_ref< array< local_ref< java::lang::String >, 1> > const &a1, local_ref< java::util::Date > const &a2)
{
	return call_static_method<
		org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_NAME(3),
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_SIGNATURE(3), 
		local_ref< java::util::Date >
	>(a0, a1, a2);
}

local_ref< java::lang::String > org::apache::http::impl::cookie::DateUtils::formatDate(local_ref< java::util::Date > const &a0)
{
	return call_static_method<
		org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_NAME(4),
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_SIGNATURE(4), 
		local_ref< java::lang::String >
	>(a0);
}

local_ref< java::lang::String > org::apache::http::impl::cookie::DateUtils::formatDate(local_ref< java::util::Date > const &a0, local_ref< java::lang::String > const &a1)
{
	return call_static_method<
		org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_NAME(5),
		org::apache::http::impl::cookie::DateUtils::J2CPP_METHOD_SIGNATURE(5), 
		local_ref< java::lang::String >
	>(a0, a1);
}



static_field<
	org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_NAME(0),
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_SIGNATURE(0),
	local_ref< java::lang::String >
> org::apache::http::impl::cookie::DateUtils::PATTERN_RFC1123;

static_field<
	org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_NAME(1),
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_SIGNATURE(1),
	local_ref< java::lang::String >
> org::apache::http::impl::cookie::DateUtils::PATTERN_RFC1036;

static_field<
	org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_NAME(2),
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_SIGNATURE(2),
	local_ref< java::lang::String >
> org::apache::http::impl::cookie::DateUtils::PATTERN_ASCTIME;

static_field<
	org::apache::http::impl::cookie::DateUtils::J2CPP_CLASS_NAME,
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_NAME(3),
	org::apache::http::impl::cookie::DateUtils::J2CPP_FIELD_SIGNATURE(3),
	local_ref< java::util::TimeZone >
> org::apache::http::impl::cookie::DateUtils::GMT;


J2CPP_DEFINE_CLASS(org::apache::http::impl::cookie::DateUtils,"org/apache/http/impl/cookie/DateUtils")
J2CPP_DEFINE_METHOD(org::apache::http::impl::cookie::DateUtils,0,"<init>","()V")
J2CPP_DEFINE_METHOD(org::apache::http::impl::cookie::DateUtils,1,"parseDate","(Ljava/lang/String;)Ljava/util/Date;")
J2CPP_DEFINE_METHOD(org::apache::http::impl::cookie::DateUtils,2,"parseDate","(Ljava/lang/String;[java.lang.String)Ljava/util/Date;")
J2CPP_DEFINE_METHOD(org::apache::http::impl::cookie::DateUtils,3,"parseDate","(Ljava/lang/String;[java.lang.StringLjava/util/Date;)Ljava/util/Date;")
J2CPP_DEFINE_METHOD(org::apache::http::impl::cookie::DateUtils,4,"formatDate","(Ljava/util/Date;)Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::impl::cookie::DateUtils,5,"formatDate","(Ljava/util/Date;Ljava/lang/String;)Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::impl::cookie::DateUtils,6,"<clinit>","()V")
J2CPP_DEFINE_FIELD(org::apache::http::impl::cookie::DateUtils,0,"PATTERN_RFC1123","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::impl::cookie::DateUtils,1,"PATTERN_RFC1036","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::impl::cookie::DateUtils,2,"PATTERN_ASCTIME","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::impl::cookie::DateUtils,3,"GMT","Ljava/util/TimeZone;")

} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_IMPL_COOKIE_DATEUTILS_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
