/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: java.net.ProxySelector
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_NET_PROXYSELECTOR_HPP_DECL
#define J2CPP_JAVA_NET_PROXYSELECTOR_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace util { class List; } } }
namespace j2cpp { namespace java { namespace net { class SocketAddress; } } }
namespace j2cpp { namespace java { namespace net { class URI; } } }
namespace j2cpp { namespace java { namespace io { class IOException; } } }


#include <java/io/IOException.hpp>
#include <java/lang/Object.hpp>
#include <java/net/SocketAddress.hpp>
#include <java/net/URI.hpp>
#include <java/util/List.hpp>


namespace j2cpp {

namespace java { namespace net {

	class ProxySelector;
	class ProxySelector
		: public object<ProxySelector>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)

		explicit ProxySelector(jobject jobj)
		: object<ProxySelector>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;


		ProxySelector();
		static local_ref< java::net::ProxySelector > getDefault();
		static void setDefault(local_ref< java::net::ProxySelector >  const&);
		local_ref< java::util::List > select(local_ref< java::net::URI >  const&);
		void connectFailed(local_ref< java::net::URI >  const&, local_ref< java::net::SocketAddress >  const&, local_ref< java::io::IOException >  const&);
	}; //class ProxySelector

} //namespace net
} //namespace java

} //namespace j2cpp

#endif //J2CPP_JAVA_NET_PROXYSELECTOR_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_NET_PROXYSELECTOR_HPP_IMPL
#define J2CPP_JAVA_NET_PROXYSELECTOR_HPP_IMPL

namespace j2cpp {



java::net::ProxySelector::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}


java::net::ProxySelector::ProxySelector()
: object<java::net::ProxySelector>(
	call_new_object<
		java::net::ProxySelector::J2CPP_CLASS_NAME,
		java::net::ProxySelector::J2CPP_METHOD_NAME(0),
		java::net::ProxySelector::J2CPP_METHOD_SIGNATURE(0)
	>()
)
{
}


local_ref< java::net::ProxySelector > java::net::ProxySelector::getDefault()
{
	return call_static_method<
		java::net::ProxySelector::J2CPP_CLASS_NAME,
		java::net::ProxySelector::J2CPP_METHOD_NAME(1),
		java::net::ProxySelector::J2CPP_METHOD_SIGNATURE(1), 
		local_ref< java::net::ProxySelector >
	>();
}

void java::net::ProxySelector::setDefault(local_ref< java::net::ProxySelector > const &a0)
{
	return call_static_method<
		java::net::ProxySelector::J2CPP_CLASS_NAME,
		java::net::ProxySelector::J2CPP_METHOD_NAME(2),
		java::net::ProxySelector::J2CPP_METHOD_SIGNATURE(2), 
		void
	>(a0);
}

local_ref< java::util::List > java::net::ProxySelector::select(local_ref< java::net::URI > const &a0)
{
	return call_method<
		java::net::ProxySelector::J2CPP_CLASS_NAME,
		java::net::ProxySelector::J2CPP_METHOD_NAME(3),
		java::net::ProxySelector::J2CPP_METHOD_SIGNATURE(3), 
		local_ref< java::util::List >
	>(get_jobject(), a0);
}

void java::net::ProxySelector::connectFailed(local_ref< java::net::URI > const &a0, local_ref< java::net::SocketAddress > const &a1, local_ref< java::io::IOException > const &a2)
{
	return call_method<
		java::net::ProxySelector::J2CPP_CLASS_NAME,
		java::net::ProxySelector::J2CPP_METHOD_NAME(4),
		java::net::ProxySelector::J2CPP_METHOD_SIGNATURE(4), 
		void
	>(get_jobject(), a0, a1, a2);
}


J2CPP_DEFINE_CLASS(java::net::ProxySelector,"java/net/ProxySelector")
J2CPP_DEFINE_METHOD(java::net::ProxySelector,0,"<init>","()V")
J2CPP_DEFINE_METHOD(java::net::ProxySelector,1,"getDefault","()Ljava/net/ProxySelector;")
J2CPP_DEFINE_METHOD(java::net::ProxySelector,2,"setDefault","(Ljava/net/ProxySelector;)V")
J2CPP_DEFINE_METHOD(java::net::ProxySelector,3,"select","(Ljava/net/URI;)Ljava/util/List;")
J2CPP_DEFINE_METHOD(java::net::ProxySelector,4,"connectFailed","(Ljava/net/URI;Ljava/net/SocketAddress;Ljava/io/IOException;)V")

} //namespace j2cpp

#endif //J2CPP_JAVA_NET_PROXYSELECTOR_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
