/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: org.apache.http.cookie.Cookie
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_COOKIE_COOKIE_HPP_DECL
#define J2CPP_ORG_APACHE_HTTP_COOKIE_COOKIE_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace util { class Date; } } }


#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>
#include <java/util/Date.hpp>


namespace j2cpp {

namespace org { namespace apache { namespace http { namespace cookie {

	class Cookie;
	class Cookie
		: public object<Cookie>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_METHOD(7)
		J2CPP_DECLARE_METHOD(8)
		J2CPP_DECLARE_METHOD(9)
		J2CPP_DECLARE_METHOD(10)
		J2CPP_DECLARE_METHOD(11)

		explicit Cookie(jobject jobj)
		: object<Cookie>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;


		local_ref< java::lang::String > getName();
		local_ref< java::lang::String > getValue();
		local_ref< java::lang::String > getComment();
		local_ref< java::lang::String > getCommentURL();
		local_ref< java::util::Date > getExpiryDate();
		jboolean isPersistent();
		local_ref< java::lang::String > getDomain();
		local_ref< java::lang::String > getPath();
		local_ref< array<jint,1> > getPorts();
		jboolean isSecure();
		jint getVersion();
		jboolean isExpired(local_ref< java::util::Date >  const&);
	}; //class Cookie

} //namespace cookie
} //namespace http
} //namespace apache
} //namespace org

} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_COOKIE_COOKIE_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_COOKIE_COOKIE_HPP_IMPL
#define J2CPP_ORG_APACHE_HTTP_COOKIE_COOKIE_HPP_IMPL

namespace j2cpp {



org::apache::http::cookie::Cookie::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

local_ref< java::lang::String > org::apache::http::cookie::Cookie::getName()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(0),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(0), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< java::lang::String > org::apache::http::cookie::Cookie::getValue()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(1),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(1), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< java::lang::String > org::apache::http::cookie::Cookie::getComment()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(2),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(2), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< java::lang::String > org::apache::http::cookie::Cookie::getCommentURL()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(3),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(3), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< java::util::Date > org::apache::http::cookie::Cookie::getExpiryDate()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(4),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(4), 
		local_ref< java::util::Date >
	>(get_jobject());
}

jboolean org::apache::http::cookie::Cookie::isPersistent()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(5),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(5), 
		jboolean
	>(get_jobject());
}

local_ref< java::lang::String > org::apache::http::cookie::Cookie::getDomain()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(6),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(6), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< java::lang::String > org::apache::http::cookie::Cookie::getPath()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(7),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(7), 
		local_ref< java::lang::String >
	>(get_jobject());
}

local_ref< array<jint,1> > org::apache::http::cookie::Cookie::getPorts()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(8),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(8), 
		local_ref< array<jint,1> >
	>(get_jobject());
}

jboolean org::apache::http::cookie::Cookie::isSecure()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(9),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(9), 
		jboolean
	>(get_jobject());
}

jint org::apache::http::cookie::Cookie::getVersion()
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(10),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(10), 
		jint
	>(get_jobject());
}

jboolean org::apache::http::cookie::Cookie::isExpired(local_ref< java::util::Date > const &a0)
{
	return call_method<
		org::apache::http::cookie::Cookie::J2CPP_CLASS_NAME,
		org::apache::http::cookie::Cookie::J2CPP_METHOD_NAME(11),
		org::apache::http::cookie::Cookie::J2CPP_METHOD_SIGNATURE(11), 
		jboolean
	>(get_jobject(), a0);
}


J2CPP_DEFINE_CLASS(org::apache::http::cookie::Cookie,"org/apache/http/cookie/Cookie")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,0,"getName","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,1,"getValue","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,2,"getComment","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,3,"getCommentURL","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,4,"getExpiryDate","()Ljava/util/Date;")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,5,"isPersistent","()Z")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,6,"getDomain","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,7,"getPath","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,8,"getPorts","()[I")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,9,"isSecure","()Z")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,10,"getVersion","()I")
J2CPP_DEFINE_METHOD(org::apache::http::cookie::Cookie,11,"isExpired","(Ljava/util/Date;)Z")

} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_COOKIE_COOKIE_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
