/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: org.apache.http.params.CoreProtocolPNames
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_PARAMS_COREPROTOCOLPNAMES_HPP_DECL
#define J2CPP_ORG_APACHE_HTTP_PARAMS_COREPROTOCOLPNAMES_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }


#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>


namespace j2cpp {

namespace org { namespace apache { namespace http { namespace params {

	class CoreProtocolPNames;
	class CoreProtocolPNames
		: public object<CoreProtocolPNames>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_FIELD(0)
		J2CPP_DECLARE_FIELD(1)
		J2CPP_DECLARE_FIELD(2)
		J2CPP_DECLARE_FIELD(3)
		J2CPP_DECLARE_FIELD(4)
		J2CPP_DECLARE_FIELD(5)
		J2CPP_DECLARE_FIELD(6)
		J2CPP_DECLARE_FIELD(7)

		explicit CoreProtocolPNames(jobject jobj)
		: object<CoreProtocolPNames>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;


		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(0), J2CPP_FIELD_SIGNATURE(0), local_ref< java::lang::String > > PROTOCOL_VERSION;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(1), J2CPP_FIELD_SIGNATURE(1), local_ref< java::lang::String > > HTTP_ELEMENT_CHARSET;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(2), J2CPP_FIELD_SIGNATURE(2), local_ref< java::lang::String > > HTTP_CONTENT_CHARSET;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(3), J2CPP_FIELD_SIGNATURE(3), local_ref< java::lang::String > > USER_AGENT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(4), J2CPP_FIELD_SIGNATURE(4), local_ref< java::lang::String > > ORIGIN_SERVER;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(5), J2CPP_FIELD_SIGNATURE(5), local_ref< java::lang::String > > STRICT_TRANSFER_ENCODING;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(6), J2CPP_FIELD_SIGNATURE(6), local_ref< java::lang::String > > USE_EXPECT_CONTINUE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(7), J2CPP_FIELD_SIGNATURE(7), local_ref< java::lang::String > > WAIT_FOR_CONTINUE;
	}; //class CoreProtocolPNames

} //namespace params
} //namespace http
} //namespace apache
} //namespace org

} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_PARAMS_COREPROTOCOLPNAMES_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_PARAMS_COREPROTOCOLPNAMES_HPP_IMPL
#define J2CPP_ORG_APACHE_HTTP_PARAMS_COREPROTOCOLPNAMES_HPP_IMPL

namespace j2cpp {



org::apache::http::params::CoreProtocolPNames::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(0),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(0),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::PROTOCOL_VERSION;

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(1),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(1),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::HTTP_ELEMENT_CHARSET;

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(2),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(2),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::HTTP_CONTENT_CHARSET;

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(3),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(3),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::USER_AGENT;

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(4),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(4),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::ORIGIN_SERVER;

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(5),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(5),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::STRICT_TRANSFER_ENCODING;

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(6),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(6),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::USE_EXPECT_CONTINUE;

static_field<
	org::apache::http::params::CoreProtocolPNames::J2CPP_CLASS_NAME,
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_NAME(7),
	org::apache::http::params::CoreProtocolPNames::J2CPP_FIELD_SIGNATURE(7),
	local_ref< java::lang::String >
> org::apache::http::params::CoreProtocolPNames::WAIT_FOR_CONTINUE;


J2CPP_DEFINE_CLASS(org::apache::http::params::CoreProtocolPNames,"org/apache/http/params/CoreProtocolPNames")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,0,"PROTOCOL_VERSION","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,1,"HTTP_ELEMENT_CHARSET","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,2,"HTTP_CONTENT_CHARSET","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,3,"USER_AGENT","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,4,"ORIGIN_SERVER","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,5,"STRICT_TRANSFER_ENCODING","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,6,"USE_EXPECT_CONTINUE","Ljava/lang/String;")
J2CPP_DEFINE_FIELD(org::apache::http::params::CoreProtocolPNames,7,"WAIT_FOR_CONTINUE","Ljava/lang/String;")

} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_PARAMS_COREPROTOCOLPNAMES_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
