/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: android.text.Spanned
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_TEXT_SPANNED_HPP_DECL
#define J2CPP_ANDROID_TEXT_SPANNED_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class Class; } } }
namespace j2cpp { namespace java { namespace lang { class CharSequence; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }


#include <java/lang/CharSequence.hpp>
#include <java/lang/Class.hpp>
#include <java/lang/Object.hpp>


namespace j2cpp {

namespace android { namespace text {

	class Spanned;
	class Spanned
		: public object<Spanned>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_FIELD(0)
		J2CPP_DECLARE_FIELD(1)
		J2CPP_DECLARE_FIELD(2)
		J2CPP_DECLARE_FIELD(3)
		J2CPP_DECLARE_FIELD(4)
		J2CPP_DECLARE_FIELD(5)
		J2CPP_DECLARE_FIELD(6)
		J2CPP_DECLARE_FIELD(7)
		J2CPP_DECLARE_FIELD(8)
		J2CPP_DECLARE_FIELD(9)
		J2CPP_DECLARE_FIELD(10)
		J2CPP_DECLARE_FIELD(11)
		J2CPP_DECLARE_FIELD(12)
		J2CPP_DECLARE_FIELD(13)
		J2CPP_DECLARE_FIELD(14)
		J2CPP_DECLARE_FIELD(15)

		explicit Spanned(jobject jobj)
		: object<Spanned>(jobj)
		{
		}

		operator local_ref<java::lang::CharSequence>() const;
		operator local_ref<java::lang::Object>() const;


		local_ref< array< local_ref< java::lang::Object >, 1> > getSpans(jint, jint, local_ref< java::lang::Class >  const&);
		jint getSpanStart(local_ref< java::lang::Object >  const&);
		jint getSpanEnd(local_ref< java::lang::Object >  const&);
		jint getSpanFlags(local_ref< java::lang::Object >  const&);
		jint nextSpanTransition(jint, jint, local_ref< java::lang::Class >  const&);

		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(0), J2CPP_FIELD_SIGNATURE(0), jint > SPAN_POINT_MARK_MASK;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(1), J2CPP_FIELD_SIGNATURE(1), jint > SPAN_MARK_MARK;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(2), J2CPP_FIELD_SIGNATURE(2), jint > SPAN_MARK_POINT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(3), J2CPP_FIELD_SIGNATURE(3), jint > SPAN_POINT_MARK;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(4), J2CPP_FIELD_SIGNATURE(4), jint > SPAN_POINT_POINT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(5), J2CPP_FIELD_SIGNATURE(5), jint > SPAN_PARAGRAPH;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(6), J2CPP_FIELD_SIGNATURE(6), jint > SPAN_INCLUSIVE_EXCLUSIVE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(7), J2CPP_FIELD_SIGNATURE(7), jint > SPAN_INCLUSIVE_INCLUSIVE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(8), J2CPP_FIELD_SIGNATURE(8), jint > SPAN_EXCLUSIVE_EXCLUSIVE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(9), J2CPP_FIELD_SIGNATURE(9), jint > SPAN_EXCLUSIVE_INCLUSIVE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(10), J2CPP_FIELD_SIGNATURE(10), jint > SPAN_COMPOSING;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(11), J2CPP_FIELD_SIGNATURE(11), jint > SPAN_INTERMEDIATE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(12), J2CPP_FIELD_SIGNATURE(12), jint > SPAN_USER_SHIFT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(13), J2CPP_FIELD_SIGNATURE(13), jint > SPAN_USER;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(14), J2CPP_FIELD_SIGNATURE(14), jint > SPAN_PRIORITY_SHIFT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(15), J2CPP_FIELD_SIGNATURE(15), jint > SPAN_PRIORITY;
	}; //class Spanned

} //namespace text
} //namespace android

} //namespace j2cpp

#endif //J2CPP_ANDROID_TEXT_SPANNED_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_TEXT_SPANNED_HPP_IMPL
#define J2CPP_ANDROID_TEXT_SPANNED_HPP_IMPL

namespace j2cpp {



android::text::Spanned::operator local_ref<java::lang::CharSequence>() const
{
	return local_ref<java::lang::CharSequence>(get_jobject());
}

android::text::Spanned::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

local_ref< array< local_ref< java::lang::Object >, 1> > android::text::Spanned::getSpans(jint a0, jint a1, local_ref< java::lang::Class > const &a2)
{
	return call_method<
		android::text::Spanned::J2CPP_CLASS_NAME,
		android::text::Spanned::J2CPP_METHOD_NAME(0),
		android::text::Spanned::J2CPP_METHOD_SIGNATURE(0), 
		local_ref< array< local_ref< java::lang::Object >, 1> >
	>(get_jobject(), a0, a1, a2);
}

jint android::text::Spanned::getSpanStart(local_ref< java::lang::Object > const &a0)
{
	return call_method<
		android::text::Spanned::J2CPP_CLASS_NAME,
		android::text::Spanned::J2CPP_METHOD_NAME(1),
		android::text::Spanned::J2CPP_METHOD_SIGNATURE(1), 
		jint
	>(get_jobject(), a0);
}

jint android::text::Spanned::getSpanEnd(local_ref< java::lang::Object > const &a0)
{
	return call_method<
		android::text::Spanned::J2CPP_CLASS_NAME,
		android::text::Spanned::J2CPP_METHOD_NAME(2),
		android::text::Spanned::J2CPP_METHOD_SIGNATURE(2), 
		jint
	>(get_jobject(), a0);
}

jint android::text::Spanned::getSpanFlags(local_ref< java::lang::Object > const &a0)
{
	return call_method<
		android::text::Spanned::J2CPP_CLASS_NAME,
		android::text::Spanned::J2CPP_METHOD_NAME(3),
		android::text::Spanned::J2CPP_METHOD_SIGNATURE(3), 
		jint
	>(get_jobject(), a0);
}

jint android::text::Spanned::nextSpanTransition(jint a0, jint a1, local_ref< java::lang::Class > const &a2)
{
	return call_method<
		android::text::Spanned::J2CPP_CLASS_NAME,
		android::text::Spanned::J2CPP_METHOD_NAME(4),
		android::text::Spanned::J2CPP_METHOD_SIGNATURE(4), 
		jint
	>(get_jobject(), a0, a1, a2);
}


static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(0),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(0),
	jint
> android::text::Spanned::SPAN_POINT_MARK_MASK;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(1),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(1),
	jint
> android::text::Spanned::SPAN_MARK_MARK;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(2),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(2),
	jint
> android::text::Spanned::SPAN_MARK_POINT;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(3),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(3),
	jint
> android::text::Spanned::SPAN_POINT_MARK;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(4),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(4),
	jint
> android::text::Spanned::SPAN_POINT_POINT;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(5),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(5),
	jint
> android::text::Spanned::SPAN_PARAGRAPH;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(6),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(6),
	jint
> android::text::Spanned::SPAN_INCLUSIVE_EXCLUSIVE;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(7),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(7),
	jint
> android::text::Spanned::SPAN_INCLUSIVE_INCLUSIVE;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(8),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(8),
	jint
> android::text::Spanned::SPAN_EXCLUSIVE_EXCLUSIVE;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(9),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(9),
	jint
> android::text::Spanned::SPAN_EXCLUSIVE_INCLUSIVE;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(10),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(10),
	jint
> android::text::Spanned::SPAN_COMPOSING;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(11),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(11),
	jint
> android::text::Spanned::SPAN_INTERMEDIATE;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(12),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(12),
	jint
> android::text::Spanned::SPAN_USER_SHIFT;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(13),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(13),
	jint
> android::text::Spanned::SPAN_USER;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(14),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(14),
	jint
> android::text::Spanned::SPAN_PRIORITY_SHIFT;

static_field<
	android::text::Spanned::J2CPP_CLASS_NAME,
	android::text::Spanned::J2CPP_FIELD_NAME(15),
	android::text::Spanned::J2CPP_FIELD_SIGNATURE(15),
	jint
> android::text::Spanned::SPAN_PRIORITY;


J2CPP_DEFINE_CLASS(android::text::Spanned,"android/text/Spanned")
J2CPP_DEFINE_METHOD(android::text::Spanned,0,"getSpans","(IILjava/lang/Class;)[java.lang.Object")
J2CPP_DEFINE_METHOD(android::text::Spanned,1,"getSpanStart","(Ljava/lang/Object;)I")
J2CPP_DEFINE_METHOD(android::text::Spanned,2,"getSpanEnd","(Ljava/lang/Object;)I")
J2CPP_DEFINE_METHOD(android::text::Spanned,3,"getSpanFlags","(Ljava/lang/Object;)I")
J2CPP_DEFINE_METHOD(android::text::Spanned,4,"nextSpanTransition","(IILjava/lang/Class;)I")
J2CPP_DEFINE_FIELD(android::text::Spanned,0,"SPAN_POINT_MARK_MASK","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,1,"SPAN_MARK_MARK","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,2,"SPAN_MARK_POINT","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,3,"SPAN_POINT_MARK","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,4,"SPAN_POINT_POINT","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,5,"SPAN_PARAGRAPH","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,6,"SPAN_INCLUSIVE_EXCLUSIVE","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,7,"SPAN_INCLUSIVE_INCLUSIVE","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,8,"SPAN_EXCLUSIVE_EXCLUSIVE","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,9,"SPAN_EXCLUSIVE_INCLUSIVE","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,10,"SPAN_COMPOSING","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,11,"SPAN_INTERMEDIATE","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,12,"SPAN_USER_SHIFT","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,13,"SPAN_USER","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,14,"SPAN_PRIORITY_SHIFT","I")
J2CPP_DEFINE_FIELD(android::text::Spanned,15,"SPAN_PRIORITY","I")

} //namespace j2cpp

#endif //J2CPP_ANDROID_TEXT_SPANNED_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
