/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: android.content.SyncStatusObserver
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_CONTENT_SYNCSTATUSOBSERVER_HPP_DECL
#define J2CPP_ANDROID_CONTENT_SYNCSTATUSOBSERVER_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class Object; } } }


#include <java/lang/Object.hpp>


namespace j2cpp {

namespace android { namespace content {

	class SyncStatusObserver;
	class SyncStatusObserver
		: public object<SyncStatusObserver>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)

		explicit SyncStatusObserver(jobject jobj)
		: object<SyncStatusObserver>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;


		void onStatusChanged(jint);
	}; //class SyncStatusObserver

} //namespace content
} //namespace android

} //namespace j2cpp

#endif //J2CPP_ANDROID_CONTENT_SYNCSTATUSOBSERVER_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_CONTENT_SYNCSTATUSOBSERVER_HPP_IMPL
#define J2CPP_ANDROID_CONTENT_SYNCSTATUSOBSERVER_HPP_IMPL

namespace j2cpp {



android::content::SyncStatusObserver::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

void android::content::SyncStatusObserver::onStatusChanged(jint a0)
{
	return call_method<
		android::content::SyncStatusObserver::J2CPP_CLASS_NAME,
		android::content::SyncStatusObserver::J2CPP_METHOD_NAME(0),
		android::content::SyncStatusObserver::J2CPP_METHOD_SIGNATURE(0), 
		void
	>(get_jobject(), a0);
}


J2CPP_DEFINE_CLASS(android::content::SyncStatusObserver,"android/content/SyncStatusObserver")
J2CPP_DEFINE_METHOD(android::content::SyncStatusObserver,0,"onStatusChanged","(I)V")

} //namespace j2cpp

#endif //J2CPP_ANDROID_CONTENT_SYNCSTATUSOBSERVER_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
